"""Added fields to Payment (faile_reason, processing_started_at, webhook_attempts, webhook_delivered_at) and to PaymentOutbox (last_error)

Revision ID: 8febac00d5b3
Revises: d338248644c5
Create Date: 2026-10-07 18:49:11.887981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8febac00d5b3"
down_revision: Union[str, None] = "d338248644c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("faile_reason", sa.Text(), nullable=True))
    op.add_column(
        "payments",
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "payments",
        sa.Column("webhook_attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "payments",
        sa.Column("webhook_delivered_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("payments_outbox", sa.Column("last_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments_outbox", "last_error")
    op.drop_column("payments", "webhook_delivered_at")
    op.drop_column("payments", "webhook_attempts")
    op.drop_column("payments", "processing_started_at")
    op.drop_column("payments", "faile_reason")
    # ### end Alembic commands ###
